#!/usr/bin/env bash
# ============================================================================
# measure-cu.sh — Run the integration test suite end-to-end, then aggregate
# per-instruction Compute-Unit (CU) usage from .anchor/program-logs/*.log
# and write a human-readable summary to docs/PERFORMANCE.md (overwritten).
#
# Prerequisite: nothing — the script invokes `pnpm test` (which spawns its own
# test-validator via anchor.toml). If a manual validator is already running,
# stop it first or pass --skip-test to only re-aggregate.
#
# Usage:
#   ./scripts/measure-cu.sh               # full run: tests + aggregate
#   ./scripts/measure-cu.sh --skip-test   # only aggregate existing logs
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

LOG_DIR=".anchor/program-logs"
OUT=docs/PERFORMANCE.md

SKIP_TEST=false
for arg in "$@"; do
  case "$arg" in
    --skip-test) SKIP_TEST=true ;;
  esac
done

if ! $SKIP_TEST; then
  echo "==> running pnpm test (validator spawned by anchor)"
  pnpm test || {
    code=$?
    echo "==> WARNING: pnpm test exited $code. Aggregating whatever logs exist anyway."
  }
fi

if [[ ! -d "$LOG_DIR" ]]; then
  echo "ERROR: $LOG_DIR not found. Run with tests at least once first."
  exit 1
fi

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# Lines look like:
#   Program <id> consumed 1234 of 200000 compute units
# We pair them with the most recent "Program log: Instruction: <Name>" line.
awk '
  /Program log: Instruction:/ {
    sub(/.*Instruction: */, "")
    ix = $0
    next
  }
  /consumed [0-9]+ of [0-9]+ compute units/ {
    match($0, /consumed [0-9]+/)
    n = substr($0, RSTART + 9, RLENGTH - 9) + 0
    if (ix != "") {
      print ix "\t" n
      ix = ""
    }
  }
' "$LOG_DIR"/*.log > "$TMP"

if [[ ! -s "$TMP" ]]; then
  echo "ERROR: no CU samples found in $LOG_DIR. Did the tests actually run?"
  exit 1
fi

# Aggregate per instruction: min / max / mean / p95 / count
mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<'EOF'
# Compute-Unit Performance

> Auto-generated by `scripts/measure-cu.sh`. Re-run after meaningful changes
> to instruction bodies. Source: `.anchor/program-logs/*.log` "consumed" lines.
>
> Solana default CU budget per instruction = 200,000. Treat >100,000 as a
> yellow flag and >150,000 as red.

EOF

echo "## Per-instruction CU (samples from latest test run)" >> "$OUT"
echo "" >> "$OUT"
echo "| Instruction | Samples | Min | Mean | P95 | Max | Status |" >> "$OUT"
echo "|---|---:|---:|---:|---:|---:|---|" >> "$OUT"

awk -F'\t' '
  { vals[$1] = (vals[$1] == "" ? $2 : vals[$1] " " $2) }
  END {
    for (ix in vals) {
      n = split(vals[ix], v, " ")
      asort(v)
      sum = 0
      for (i = 1; i <= n; i++) sum += v[i]
      mean = sum / n
      p95idx = int(0.95 * n)
      if (p95idx < 1) p95idx = 1
      if (p95idx > n) p95idx = n
      max = v[n]
      flag = (max > 150000 ? "🔴" : (max > 100000 ? "🟡" : "✅"))
      printf "| %s | %d | %d | %.0f | %d | %d | %s |\n",
             ix, n, v[1], mean, v[p95idx], v[n], flag
    }
  }
' "$TMP" | sort >> "$OUT"

echo "" >> "$OUT"
echo "## Raw sample count" >> "$OUT"
echo "" >> "$OUT"
echo "    $(wc -l < "$TMP" | tr -d ' ') consumed-line samples across $(ls "$LOG_DIR"/*.log 2>/dev/null | wc -l | tr -d ' ') log files" >> "$OUT"
echo "" >> "$OUT"
echo "_Generated $(date -u +%Y-%m-%dT%H:%M:%SZ)_" >> "$OUT"

echo "==> wrote $OUT"
cat "$OUT"
